create table Items(
    ID int identity(1,1),
    Name not null,
    TextCode null,
    CurrencyID null,
    ProviderID null,
    Active null,
    Department null,
    Kind null,
    Description1 null,
    Description2 null,
    Class1 null,
    Class2 null,
    Tag1 null,
    Tag2 null,
    Tag3 null,
    Tag4 null,
    SmallestAmount null,
    Image null,
    BuyPrice null,
    LastSaleDate null,
    SecretDegree null,
    ShowInPOS null,
    Unit1Name null,
    Unit2Name null,
    Unit1Value null,
    Unit2Value null,
    SalePrice null,
    SalePlane null,
    Barcode1 null,
    Barcode2 null,
    DiscountBeforePrecient null,
    DiscountForGomla null,
    DiscountForHaefGomla null,
    DiscountAfterPrecient null,
    SaleTaxAddedValue null,
    BuyTaxAddedValue null,

    constraint Item_PK primary key (ID)
)
